[CmdletBinding(SupportsShouldProcess = $true)]
param(
    [Parameter(Mandatory = $false)]
    [ValidateRange(0, 3650)]
    [int]$OlderThanDays = 0,

    [Parameter(Mandatory = $false)]
    [switch]$DryRun,

    [Parameter(Mandatory = $false)]
    [switch]$Rollback,

    [Parameter(Mandatory = $false)]
    [string]$RollbackManifest,

    [Parameter(Mandatory = $false)]
    [string[]]$TargetPaths = @(
        "$env:TEMP",
        "$env:WINDIR\Temp"
    ),

    [Parameter(Mandatory = $false)]
    [string]$WorkingRoot = "$env:ProgramData\DWP-TempCleanup"
)

$ErrorActionPreference = "Stop"

# This section creates dated folders for logs, quarantine, and manifests used by cleanup and rollback.
$runStamp = Get-Date -Format "yyyyMMdd-HHmmss"
$logRoot = Join-Path -Path $WorkingRoot -ChildPath "Logs"
$quarantineRoot = Join-Path -Path $WorkingRoot -ChildPath "Quarantine"
$manifestRoot = Join-Path -Path $WorkingRoot -ChildPath "Manifests"
$logFile = Join-Path -Path $logRoot -ChildPath "temp-cleanup-$runStamp.log"

New-Item -Path $logRoot -ItemType Directory -Force | Out-Null
New-Item -Path $quarantineRoot -ItemType Directory -Force | Out-Null
New-Item -Path $manifestRoot -ItemType Directory -Force | Out-Null

function Write-Log {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Message,

        [Parameter(Mandatory = $false)]
        [ValidateSet("INFO", "WARN", "ERROR")]
        [string]$Level = "INFO"
    )

    $line = "{0} [{1}] {2}" -f (Get-Date -Format "yyyy-MM-dd HH:mm:ss"), $Level, $Message
    Add-Content -Path $logFile -Value $line
    Write-Host $line
}

function Test-FileLocked {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path
    )

    try {
        $stream = [System.IO.File]::Open($Path, [System.IO.FileMode]::Open, [System.IO.FileAccess]::ReadWrite, [System.IO.FileShare]::None)
        $stream.Close()
        return $false
    }
    catch {
        return $true
    }
}

function Get-SafeRelativePath {
    param(
        [Parameter(Mandatory = $true)]
        [string]$BasePath,

        [Parameter(Mandatory = $true)]
        [string]$FullPath
    )

    $baseResolved = [System.IO.Path]::GetFullPath($BasePath)
    $fullResolved = [System.IO.Path]::GetFullPath($FullPath)

    if (-not $fullResolved.StartsWith($baseResolved, [System.StringComparison]::OrdinalIgnoreCase)) {
        return $null
    }

    $relative = $fullResolved.Substring($baseResolved.Length).TrimStart('\\')
    return $relative
}

function Invoke-Rollback {
    param(
        [Parameter(Mandatory = $true)]
        [string]$ManifestPath
    )

    # This section restores files from quarantine using a manifest generated by a prior cleanup run.
    if (-not (Test-Path -LiteralPath $ManifestPath)) {
        throw "Rollback manifest not found: $ManifestPath"
    }

    $entries = Get-Content -Path $ManifestPath | ConvertFrom-Json
    if ($entries -isnot [System.Array]) {
        $entries = @($entries)
    }

    $restoreCount = 0
    $skipCount = 0
    $errorCount = 0

    foreach ($entry in $entries) {
        try {
            if (-not (Test-Path -LiteralPath $entry.QuarantinePath)) {
                Write-Log -Level "WARN" -Message "Rollback skip, missing quarantine file: $($entry.QuarantinePath)"
                $skipCount++
                continue
            }

            $destDir = Split-Path -Path $entry.OriginalPath -Parent
            if (-not (Test-Path -LiteralPath $destDir)) {
                New-Item -Path $destDir -ItemType Directory -Force | Out-Null
            }

            if (Test-Path -LiteralPath $entry.OriginalPath) {
                Write-Log -Level "WARN" -Message "Rollback skip, destination already exists: $($entry.OriginalPath)"
                $skipCount++
                continue
            }

            Move-Item -LiteralPath $entry.QuarantinePath -Destination $entry.OriginalPath -Force
            Write-Log -Message "Rollback restored: $($entry.OriginalPath)"
            $restoreCount++
        }
        catch {
            Write-Log -Level "ERROR" -Message "Rollback failed for $($entry.OriginalPath): $($_.Exception.Message)"
            $errorCount++
        }
    }

    Write-Log -Message "Rollback summary: Restored=$restoreCount Skipped=$skipCount Errors=$errorCount"
}

# This section validates mode and chooses either cleanup flow or rollback flow.
if ($Rollback) {
    if ([string]::IsNullOrWhiteSpace($RollbackManifest)) {
        throw "When -Rollback is used, -RollbackManifest must be provided."
    }

    Write-Log -Message "Starting rollback mode with manifest: $RollbackManifest"
    Invoke-Rollback -ManifestPath $RollbackManifest
    Write-Log -Message "Rollback completed."
    return
}

# This section calculates the file age threshold and builds the candidate file list from temp targets.
$cutoff = (Get-Date).AddDays(-1 * $OlderThanDays)
$candidates = New-Object System.Collections.Generic.List[object]

foreach ($target in $TargetPaths) {
    try {
        if (-not (Test-Path -LiteralPath $target)) {
            Write-Log -Level "WARN" -Message "Target path not found, skipping: $target"
            continue
        }

        Write-Log -Message "Scanning target path: $target"

        Get-ChildItem -LiteralPath $target -Recurse -File -Force -ErrorAction SilentlyContinue |
            Where-Object { $_.LastWriteTime -lt $cutoff } |
            ForEach-Object {
                $candidates.Add([pscustomobject]@{
                    FullName   = $_.FullName
                    BaseTarget = $target
                    LastWrite  = $_.LastWriteTime
                    Length     = $_.Length
                })
            }
    }
    catch {
        Write-Log -Level "ERROR" -Message "Failed to scan target $target: $($_.Exception.Message)"
    }
}

# This section de-duplicates files so repeated runs behave consistently and idempotently.
$uniqueCandidates = $candidates |
    Sort-Object -Property FullName -Unique

Write-Log -Message "Candidate files older than $OlderThanDays day(s): $($uniqueCandidates.Count)"

if ($DryRun) {
    # This section prints files that would be moved/deleted without changing system state.
    Write-Log -Message "DryRun enabled. No files will be changed."
    $uniqueCandidates |
        Sort-Object -Property FullName |
        Select-Object FullName, LastWrite,
        @{Name = "SizeKB"; Expression = { [math]::Round($_.Length / 1KB, 2) } } |
        Format-Table -AutoSize

    Write-Log -Message "DryRun summary: Candidates=$($uniqueCandidates.Count)"
    Write-Host "Log file: $logFile"
    return
}

# This section moves candidate files into quarantine and records a manifest for rollback.
$runQuarantine = Join-Path -Path $quarantineRoot -ChildPath $runStamp
New-Item -Path $runQuarantine -ItemType Directory -Force | Out-Null

$manifestPath = Join-Path -Path $manifestRoot -ChildPath "manifest-$runStamp.json"
$manifestItems = New-Object System.Collections.Generic.List[object]

$processed = 0
$moved = 0
$lockedSkipped = 0
$errorCount = 0
$totalBytes = 0

foreach ($item in $uniqueCandidates) {
    $processed++

    try {
        if (-not (Test-Path -LiteralPath $item.FullName)) {
            Write-Log -Level "WARN" -Message "Skip missing file (already gone): $($item.FullName)"
            continue
        }

        if (Test-FileLocked -Path $item.FullName) {
            Write-Log -Level "WARN" -Message "Skip locked file: $($item.FullName)"
            $lockedSkipped++
            continue
        }

        $relative = Get-SafeRelativePath -BasePath $item.BaseTarget -FullPath $item.FullName
        if ([string]::IsNullOrWhiteSpace($relative)) {
            Write-Log -Level "WARN" -Message "Skip file outside target root: $($item.FullName)"
            continue
        }

        $targetFolderName = ($item.BaseTarget -replace '[:\\/\s]', '_').Trim('_')
        $destPath = Join-Path -Path $runQuarantine -ChildPath (Join-Path -Path $targetFolderName -ChildPath $relative)
        $destDir = Split-Path -Path $destPath -Parent
        if (-not (Test-Path -LiteralPath $destDir)) {
            New-Item -Path $destDir -ItemType Directory -Force | Out-Null
        }

        if ($PSCmdlet.ShouldProcess($item.FullName, "Move to quarantine")) {
            Move-Item -LiteralPath $item.FullName -Destination $destPath -Force
            Write-Log -Message "Moved to quarantine: $($item.FullName) -> $destPath"

            $manifestItems.Add([pscustomobject]@{
                OriginalPath   = $item.FullName
                QuarantinePath = $destPath
                BaseTarget     = $item.BaseTarget
                LastWrite      = $item.LastWrite
                Length         = $item.Length
                RunStamp       = $runStamp
            })

            $moved++
            $totalBytes += [int64]$item.Length
        }
    }
    catch {
        Write-Log -Level "ERROR" -Message "Failed processing file $($item.FullName): $($_.Exception.Message)"
        $errorCount++
    }
}

$manifestItems | ConvertTo-Json -Depth 5 | Set-Content -Path $manifestPath -Encoding UTF8

# This section reports a cleanup summary and points to log and rollback manifest locations.
$freedMB = [math]::Round($totalBytes / 1MB, 2)
Write-Host ""
Write-Host "===== Cleanup Summary =====" -ForegroundColor Cyan
Write-Host "Processed files : $processed"
Write-Host "Moved files     : $moved"
Write-Host "Locked skipped  : $lockedSkipped"
Write-Host "Errors          : $errorCount"
Write-Host "Freed space MB  : $freedMB"
Write-Host "Log file        : $logFile"
Write-Host "Rollback file   : $manifestPath"

Write-Log -Message "Cleanup summary: Processed=$processed Moved=$moved LockedSkipped=$lockedSkipped Errors=$errorCount FreedMB=$freedMB"
Write-Log -Message "Rollback manifest: $manifestPath"
